// <auto-generated />
using System;
using System.Collections.Generic;
using LIT.Travelnize.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIT.Travelnize.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924181036_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "LIT.Travelnize.Domain.Trips.Accommodation.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Slot", "LIT.Travelnize.Domain.Trips.Accommodation.Slot#PlanningSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("Start")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Type", "LIT.Travelnize.Domain.Trips.Accommodation.Type#AccommodationType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "LIT.Travelnize.Domain.Trips.Activity.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Address", "LIT.Travelnize.Domain.Trips.Activity.Location#Location.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line2")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "LIT.Travelnize.Domain.Trips.Activity.Location#Location.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Location", "LIT.Travelnize.Domain.Trips.Destination.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Address", "LIT.Travelnize.Domain.Trips.Destination.Location#Location.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line2")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "LIT.Travelnize.Domain.Trips.Destination.Location#Location.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Slot", "LIT.Travelnize.Domain.Trips.Destination.Slot#PlanningSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("Start")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TravelSegmentId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TransportationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("PermissionLevel", "LIT.Travelnize.Domain.Trips.Participant.PermissionLevel#PermissionLevel", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TransportationId");

                    b.HasIndex("TripId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Arrival", "LIT.Travelnize.Domain.Trips.Transportation.Arrival#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Address", "LIT.Travelnize.Domain.Trips.Transportation.Arrival#Location.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line2")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "LIT.Travelnize.Domain.Trips.Transportation.Arrival#Location.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Departure", "LIT.Travelnize.Domain.Trips.Transportation.Departure#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Address", "LIT.Travelnize.Domain.Trips.Transportation.Departure#Location.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line1")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Line2")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Coordinates", "LIT.Travelnize.Domain.Trips.Transportation.Departure#Location.Coordinates#Coordinates", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Type", "LIT.Travelnize.Domain.Trips.Transportation.Type#TransportationType", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Transportations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Slot", "LIT.Travelnize.Domain.Trips.TravelSegment.Slot#PlanningSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("Start")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TravelSegments");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Slot", "LIT.Travelnize.Domain.Trips.Trip.Slot#PlanningSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("Start")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Accommodation", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Destination", null)
                        .WithMany("Accommodations")
                        .HasForeignKey("DestinationId");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Activity", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Destination", null)
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.TravelSegment", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TravelSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ResourceReference", "Image", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsExternal")
                                .HasColumnType("boolean");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Thumbnail")
                                .HasColumnType("text");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ResourceReference", "Website", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsExternal")
                                .HasColumnType("boolean");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Thumbnail")
                                .HasColumnType("text");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.Navigation("Image");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Participant", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Transportation", null)
                        .WithMany("Passengers")
                        .HasForeignKey("TransportationId");

                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("Email");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("Transportations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ResourceReference", "RouteWebsite", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsExternal")
                                .HasColumnType("boolean");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Thumbnail")
                                .HasColumnType("text");

                            b1.HasKey("TransportationId");

                            b1.ToTable("Transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId");
                        });

                    b.Navigation("RouteWebsite");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("TravelSegments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Activities");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Trip", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Transportations");

                    b.Navigation("TravelSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
