// <auto-generated />
using System;
using LIT.Travelnize.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LIT.Travelnize.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826150507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TravelSegmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TravelSegmentId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TransportationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TransportationId");

                    b.HasIndex("TripId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Transportations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TravelSegments");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Accommodation", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Destination", null)
                        .WithMany("Accommodations")
                        .HasForeignKey("DestinationId");

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AccommodationId")
                                .HasColumnType("uuid");

                            b1.HasKey("AccommodationId");

                            b1.ToTable("Accommodations");

                            b1.WithOwner()
                                .HasForeignKey("AccommodationId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Trips.AccommodationType", "Type", b1 =>
                        {
                            b1.Property<Guid>("AccommodationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AccommodationId");

                            b1.ToTable("Accommodations");

                            b1.WithOwner()
                                .HasForeignKey("AccommodationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Activity", b =>
                {
                    b.OwnsOne("LIT.Travelnize.Domain.Common.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");

                            b1.OwnsOne("LIT.Travelnize.Domain.Common.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationActivityId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision");

                                    b2.HasKey("LocationActivityId");

                                    b2.ToTable("Activities");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationActivityId");
                                });

                            b1.OwnsOne("LIT.Travelnize.Domain.Common.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("LocationActivityId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("LocationActivityId");

                                    b2.ToTable("Activities");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationActivityId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.TravelSegment", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TravelSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ExternalUrl", "ImageUrl", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");

                            b1.OwnsOne("LIT.Travelnize.Domain.Common.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("LocationDestinationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("LocationDestinationId");

                                    b2.ToTable("Destinations");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationDestinationId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ExternalUrl", "Website", b1 =>
                        {
                            b1.Property<Guid>("DestinationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("DestinationId");

                            b1.ToTable("Destinations");

                            b1.WithOwner()
                                .HasForeignKey("DestinationId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();

                    b.Navigation("ImageUrl");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Participant", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Transportation", null)
                        .WithMany("Passengers")
                        .HasForeignKey("TransportationId");

                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.PermissionLevel", "PermissionLevel", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("Email");

                    b.Navigation("PermissionLevel")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("Transportations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Location", "Arrival", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid");

                            b1.HasKey("TransportationId");

                            b1.ToTable("Transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId");

                            b1.OwnsOne("LIT.Travelnize.Domain.Common.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("LocationTransportationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("LocationTransportationId");

                                    b2.ToTable("Transportations");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationTransportationId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.Location", "Departure", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid");

                            b1.HasKey("TransportationId");

                            b1.ToTable("Transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId");

                            b1.OwnsOne("LIT.Travelnize.Domain.Common.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("LocationTransportationId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("LocationTransportationId");

                                    b2.ToTable("Transportations");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationTransportationId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Common.ExternalUrl", "RouteLink", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TransportationId");

                            b1.ToTable("Transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId");
                        });

                    b.OwnsOne("LIT.Travelnize.Domain.Trips.TransportationType", "Type", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TransportationId");

                            b1.ToTable("Transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId");
                        });

                    b.Navigation("Arrival")
                        .IsRequired();

                    b.Navigation("Departure")
                        .IsRequired();

                    b.Navigation("RouteLink")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.HasOne("LIT.Travelnize.Domain.Trips.Trip", null)
                        .WithMany("TravelSegments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LIT.Travelnize.Domain.Common.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("TravelSegmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TravelSegmentId");

                            b1.ToTable("TravelSegments");

                            b1.WithOwner()
                                .HasForeignKey("TravelSegmentId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Trip", b =>
                {
                    b.OwnsOne("LIT.Travelnize.Domain.Common.DateRange", "TravelPeriod", b1 =>
                        {
                            b1.Property<Guid>("TripId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TripId");

                            b1.ToTable("Trips");

                            b1.WithOwner()
                                .HasForeignKey("TripId");
                        });

                    b.Navigation("TravelPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Destination", b =>
                {
                    b.Navigation("Accommodations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Transportation", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.TravelSegment", b =>
                {
                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("LIT.Travelnize.Domain.Trips.Trip", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Transportations");

                    b.Navigation("TravelSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
