# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish
      run: dotnet publish -c Release -o output

    # Deployment auf den vServer
    - name: Deploy to Strato vServer
      env:
        SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
        SERVER_USER: ${{ secrets.DEV_SERVER_USER }}
        SERVER_SSH_KEY: ${{ secrets.DEV_SERVER_SSH_KEY }}
      run: |
        # Erstelle eine ZIP-Datei für die Veröffentlichung
        cd output
        zip -r ../deploy.zip .
        cd ..

        # Übertrage die ZIP-Datei auf den vServer
        scp -i $SERVER_SSH_KEY -o StrictHostKeyChecking=no deploy.zip $SERVER_USER@$SERVER_IP:/path/to/deploy

        # Entpacke die ZIP-Datei und führe die Anwendung aus
        ssh -i $SERVER_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "unzip -o /travelnize/deploy.zip -d /travelnize && cd /travelnize/deploy"
